---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.5.8
    commands:
      - dapper precheck
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: stage-binaries
    image: rancher/dapper:v0.5.8
    commands:
      - "cp -r ./bin/* ./package/"
    when:
      event:
        - push
        - tag

  - name: docker-publish-master
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
      context: package/
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/terraform-provider-harvester"
      tag: ${DRONE_BRANCH}-head-amd64
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/v*"
      event:
        - push

  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
        - "VERSION=${DRONE_TAG}"
      context: package/
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/terraform-provider-harvester"
      tag: "${DRONE_TAG}-amd64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest-master
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
      target: "rancher/terraform-provider-harvester:${DRONE_BRANCH}-head"
      template: "rancher/terraform-provider-harvester:${DRONE_BRANCH}-head-ARCH"
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/v*"
      event:
        - push

  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
      target: "rancher/terraform-provider-harvester:${DRONE_TAG}"
      template: "rancher/terraform-provider-harvester:${DRONE_TAG}-ARCH"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

depends_on:
  - amd64
