---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-release-binary
  image: rancher/dapper:v0.5.8
  environment:
    CROSS: 1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

- name: gpg-sign-release
  image: plugins/gpgsign
  settings:
    key:
      from_secret: gpg_private_key
    passphrase:
      from_secret: gpg_passphrase
    files:
    - dist/artifacts/terraform-provider-harvester_*_SHA256SUMS
    detach_sign: true
    armor: false
  when:
    event:
    - tag

- name: github-binary-prerelease
  image: plugins/github-release
  settings:
    prerelease: true
    files:
    - dist/artifacts/terraform-provider-harvester_*
    api_key:
      from_secret: github_token
  when:
    ref:
      include:
      - "refs/tags/*rc*"
    event:
    - tag

- name: github-binary-release
  image: plugins/github-release
  settings:
    files:
    - dist/artifacts/terraform-provider-harvester_*
    api_key:
      from_secret: github_token
  when:
    ref:
      exclude:
      - "refs/tags/*rc*"
    event:
    - tag

- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request

- name: stage-binaries
  image: rancher/dapper:v0.5.8
  commands:
  - "cp -r ./bin/terraform-provider-harvester ./package/"
  when:
    ref:
      include:
      - "refs/heads/master"
    event:
    - push

- name: docker-publish-master
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: "rancher/terraform-provider-harvester"
    tag: ${DRONE_BRANCH}-head-amd64
  when:
    ref:
      include:
      - "refs/heads/master"
    event:
    - push

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-master
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    target: "rancher/terraform-provider-harvester:${DRONE_BRANCH}-head"
    template: "rancher/terraform-provider-harvester:${DRONE_BRANCH}-head-ARCH"
  when:
    ref:
      include:
      - "refs/heads/master"
    event:
    - push

depends_on:
- default
