version: 2
run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - whitespace
    - unused
    - ineffassign
    - prealloc
    - goconst
    - misspell
    - gosec
  enable-all: false
  disable-all: true
  fast: false
  formatters:
    enable:
      - gofmt
  settings:
    goimports:
      local-prefixes: github.com/harvester/terraform-provider-harvester
  exclude-dirs:
    - go/pkg/mod
