run:
  timeout: 5m
issues:
  exclude-dirs:
    - go/pkg/mod
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - whitespace
    - unused
    - ineffassign
    - prealloc
    - stylecheck
    - goconst
    - gosimple
    - misspell
    - gosec
  enable-all: false
  disable-all: true
  fast: false
linters-settings:
  goimports:
    local-prefixes: github.com/harvester/terraform-provider-harvester
