#!/bin/bash
set -e

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"
PACKAGE_DIR="${TOP_DIR}/package"

source $SCRIPTS_DIR/version

cd $TOP_DIR

if [ "${GIT_TAG}" != "${VERSION}" ]; then
  PROVIDER_VERSION="0.0.0-dev"
else
  PROVIDER_VERSION=${VERSION#"v"}
fi

TAG=${TAG:-${VERSION}}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

mkdir -p dist/artifacts
cp bin/terraform-provider-harvester-* dist/artifacts/

cd ${PACKAGE_DIR}

REPO=${REPO:-rancher}
IMAGE=${REPO}/terraform-provider-harvester:${TAG}
DOCKERFILE=Dockerfile

rm -rf ./terraform-provider-harvester-*
cp ../bin/terraform-provider-harvester-* .

docker run --privileged --rm tonistiigi/binfmt --install all
buildx create --platform linux/arm64,linux/amd64 --use
buildx ls

# In old docker version, it doesn't support multiple values in --platform with --load.
# So we only load image with current platform.
# Ref: https://github.com/docker/buildx/issues/59#issuecomment-616050491
buildx build \
  --build-arg PROVIDER_VERSION=${PROVIDER_VERSION} \
  --platform linux/amd64,linux/arm64 \
  -f ${DOCKERFILE} -t ${IMAGE} .
buildx build --load \
  --build-arg PROVIDER_VERSION=${PROVIDER_VERSION} \
  -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
