#!/bin/bash
set -e

cd $(dirname $0)/..

if [ -f ./kubeconfig_test.yaml ] ; then
  export KUBECONFIG="$(pwd)/kubeconfig_test.yaml"
  export TF_ACC=1
  # Avoid timeout after 10 minutes https://pkg.go.dev/cmd/go#hdr-Testing_flags
  export EXTRA_OPTIONS=("-timeout" "0")
fi

echo Running tests:
go test \
  -v \
  -cover \
  -coverprofile=coverage.out \
  -tags=test \
  "${EXTRA_OPTIONS[@]}" \
  . ./...

go tool cover \
  -html=coverage.out \
  -o coverage.html
