#!/bin/bash
set -e

cd $(dirname $0)/..

if [ -f ./kubeconfig_test.yaml ] ; then
  export KUBECONFIG="$(pwd)/kubeconfig_test.yaml"
  export TF_ACC=1
fi

echo Running tests:
go test -v -cover -tags=test . ./...
