#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

PACKAGES="$(go list ./...)"

if ! command -v golangci-lint; then
    echo Skipping validation: no golangci-lint available
    exit
fi

echo Running validation: golangci-lint
golangci-lint run --timeout 5m

echo Running validation: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
